# Generated by Django 3.2.5 on 2021-12-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_clubmemberapplications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClubOfficer',
        ),
    ]
